name: LeetHub Supports

on:
  push:
    branches:
      - "main"

jobs:
  leethub_support:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Move questions to leetcode directory
        run: python3 .github/workflows/scripts/leethub_support.py
      
      - name: Run autopep8
        run: |
          pip3 install autopep8
          autopep8 -i -r leetcode
      
      - name: Format go answers
        run: .github/workflows/scripts/go_handler.sh

      - name: Commit files
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add -A
          git commit --amend -C HEAD
        
      - name: Merge commits authored today
        run: .github/workflows/scripts/merge_commits.sh

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          force: true
